#!/usr/bin/env ruby
require 'open3'; require 'ww'
Open3.popen3("#{ARGV[0] == 'all' ? 'cat' : 'tail -f'} log/access.log") do |stdin, stdout, stderr, thread|
  hosts = {}
  while line = stdout.gets do
    t = line.split ' '
    status,method,addr,action,mime = [t[3],t[5],t[6],t[8],t[9]]
    unless !addr || hosts[addr.R.host] || method == 'CONNECT'
      hosts[addr.R.host] = true
      puts "\e[7m" + method + "\e[0m \e[32;1m" + status + " \e[7m" + addr + "\e[0m " + "#{action} #{mime}"
    end
  end
end
