#!/bin/sh

# Alpine https://www.alpinelinux.org/
which apk && su -c 'apk add alpine-sdk iptables ip6tables graphicsmagick ruby ruby-dev openssl-dev socat syncthing libexif-dev libxslt-dev taglib squid'

# Arch https://www.archlinux.org/
which pacman && su -c 'pacman -S base-devel git graphicsmagick parallel pygmentize ruby ruby-bundler ruby-rdoc socat squid syncthing taglib'
which pacman && su -c '/usr/lib/squid/security_file_certgen -c -s /var/cache/squid/ssl_db -M 4MB'

# Debian https://www.debian.org/
which apt-add-repository && su -c 'apt-get install build-essential graphicsmagick git ruby ruby-dev bundler grep file libexif-dev libssl-dev libtag1-dev libxslt-dev libzip-dev socat squid make syncthing libffi-dev'

# Termux https://termux.com/
which pkg && pkg install graphicsmagick git ruby grep file findutils pkg-config libiconv libexif libprotobuf libxslt clang taglib squid make syncthing libffi libcap libcrypt openssl-tool zlib

# Void https://voidlinux.org
which xbps-install && su -c 'xbps-install -S base-devel git GraphicsMagick libexif-devel parallel python3-Pygments ruby ruby-devel socat squid syncthing taglib-devel'

# Ruby
which bundle || gem install bundler
bundle install

# create maildir
mkdir -p ~/web/mail/{cur,new,tmp}

# generate and import certificate
./bin/certificate
