source "https://rubygems.org/"
gem 'brotli'
gem 'chronic'
gem 'exif'
gem 'file-tail'
gem 'icalendar'
gem 'linkeddata'
gem 'mail'
gem 'nokogumbo'
gem 'pdf-reader'
gem 'pry'
gem 'pry-doc'
gem 'rack'
gem 'redcarpet'
gem 'tzinfo-data'
gem 'unicorn'
gem 'webvtt-ruby', git: 'https://github.com/opencoconut/webvtt-ruby', branch: 'master'
