#!/bin/sh
uid=$(id -u)

## install Distro packages

# Alpine https://www.alpinelinux.org/
which apk && sudo apk add alpine-sdk build-base linux-headers ruby ruby-dev ruby-json ruby-bigdecimal ruby-bundler openssl-dev parallel py3-pip findutils grep socat libexif-dev libxslt-dev squid taglib-dev tmux py3-pygments p11-kit-trust
which apk && sudo /usr/lib/squid/security_file_certgen -c -s /var/cache/squid/ssl_db -M 4MB && sudo chown -R $uid:$uid /var/cache/squid

# Arch https://www.archlinux.org/
which pacman && sudo pacman -S --needed base-devel git libexif parallel pygmentize ruby ruby-bundler socat squid taglib tmux
which pacman && sudo /usr/lib/squid/security_file_certgen -c -s /var/cache/squid/ssl_db -M 4MB

# Chromebrew https://github.com/skycocker/chromebrew
which crew && crew install buildessential libexif parallel socat taglib tmux

# Debian https://www.debian.org/
which apt-add-repository && sudo apt-get install build-essential git parallel ruby ruby-dev bundler grep file libexif-dev libssl-dev libtag1-dev libxslt-dev libzip-dev socat squid make tmux libffi-dev

# Termux https://termux.com/
which pkg && pkg install git ruby grep file findutils pkg-config libiconv libexif libprotobuf libxslt parallel clang taglib squid make libffi libcap libcrypt openssl-tool tmux tsu zlib

# Void https://voidlinux.org
which xbps-install && sudo xbps-install -S base-devel curl git libexif-devel libltdl-devel libressl-devel parallel poppler-utils python3-Pygments ruby ruby-devel socat squid taglib-devel tmux
which xbps-install && sudo /usr/libexec/squid/security_file_certgen -c -s /var/cache/squid/ssl_db -M 4MB

## install Language packages

# Python
which pygmentize || pip install pygments

# Ruby
gem install nokogiri -- --use-system-libraries
which bundle || gem install bundler
bundle install

## initialize file state
mkdir -p ~/web/mail/{cur,new,tmp}
touch ~/web/web.log

## install HTTPS certificate
./bin/certificate
