#!/bin/sh
iptables  -A INPUT  -p tcp --sport $1 -j ACCEPT
ip6tables -A INPUT  -p tcp --sport $1 -j ACCEPT
iptables  -A OUTPUT -p tcp --dport $1 -j ACCEPT
ip6tables -A OUTPUT -p tcp --dport $1 -j ACCEPT
iptables  -A INPUT  -p udp --sport $1 -j ACCEPT
ip6tables -A INPUT  -p udp --sport $1 -j ACCEPT
iptables  -A OUTPUT -p udp --dport $1 -j ACCEPT
ip6tables -A OUTPUT -p udp --dport $1 -j ACCEPT
