source /etc/profile
PS1=' \w '
export HISTSIZE=10000
export EDITOR=emacs
export PAGER=less
export BROWSER=c
export XTIDE_DEFAULT_LOCATION=Neponset
export HFILE_PATH=/usr/share/xtide/harmonics.tcd
export LANG=en_US.UTF-8
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
alias a='alsamixer'
alias ka=killall
alias fd='find . | grep -i'
export GREP_COLORS=always
alias px='ps aux | grep -v grep | grep'
alias gt='grep --text'
alias gst='git status'
alias gd='git diff'
alias gpl='git pull origin'
alias gp='git commit -a -m'
alias gpr='git push ssh://ubuntu@mw.logbook.am:/home/ubuntu/src/WebServer master;git push git@gitlab.com:ix/WebServer.git master; git push ssh://git@github.com/cubedcod/WebServer.git master'
alias lS='du -k|sort -n'
alias l='ls -al'
alias ll='ls -alt|less'
alias y='cd ~/src/WebServer'
alias m=mpv
alias mp='mpv -shuffle .'
alias tp='cat /sys/devices/virtual/thermal/thermal_zone*/temp'
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec sway; fi
